name = "v2ray-worker-tepo18"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

account_id = "YOUR_ACCOUNT_ID"

kv_namespaces = [
  { binding = "settings", id = "YOUR_KV_ID" }
]
