name = "sab"      # فقط حروف کوچک، اعداد و -
main = "src/worker.ts"
compatibility_date = "2025-10-31"
compatibility_flags = ["nodejs_compat"]

account_id = "79455e137356a49f59076d6e218a1f48"   # اکانت واقعی تو

kv_namespaces = [
  { binding = "settings", id = "c63c9e34865e4ca186ebee65841a848e" }  # KV واقعی
]
