name: Deploy Worker
on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.16.0"
        cache: "npm"

    - name: Install Wrangler
      run: npm install --save-dev wrangler@latest

    - name: Build Worker
      run: npx wrangler build

    - name: Add Header
      run: |
        cp ${{ github.workspace }}/dist/worker.js ${{ github.workspace }}/dist/worker-original.js
        echo -e "/*!\n  * v2ray Subscription Worker (${{ github.sha }})\n  * Copyright 2024 Vahid Farid\n  * Licensed under GPLv3\n  */\n\n" > ${{ github.workspace }}/dist/worker.js
        cat ${{ github.workspace }}/dist/worker-original.js >> ${{ github.workspace }}/dist/worker.js

    - name: Deploy to Cloudflare
      run: |
        sed -i "s/KV_NAME/${{ secrets.KV_NAME }}/g" wrangler.toml
        npx wrangler deploy --api-token ${{ secrets.CF_API_TOKEN }} --account-id ${{ secrets.CF_ACCOUNT_ID }}
